feat/pageClassroom
sumelms/frontend pull request #163
Opened 2022-11-23 18:30 UTC by mouracamila

create the page structure #149  classroom progress widget and the classroom accordion

2022-11-25 13:12 UTC, arianerocha requested changes

2022-11-25 13:12 UTC, arianerocha commented on src/modules/Classroom/containers/ClassroomView.tsx
> +import { Accordion, Button } from 'flowbite-react';
can you move this into a `Classroom/containers/Classroom/index.ts` or `Classroom/containers/ClassroomOverview/index.ts` to keep the structure consistent with the course module?

2022-11-25 13:12 UTC, arianerocha commented on src/modules/Classroom/containers/ClassroomView.tsx
> +      data: '18/02/2022',
Please change it to something like
````
{
  title: '',
  reminderAt: ''
}
````

to make it easy to extract to the mock server later.

2022-11-25 13:12 UTC, arianerocha commented on src/modules/Classroom/components/CardReminder/index.tsx
> +  data?: string;
maybe `reminderAt` or `reminderDate` ?

2023-03-04 16:29 UTC, rluders commented
Drop

2023-03-04 16:29 UTC, closed without merging