Fixing containers and moving files around
sumelms/frontend pull request #36
Opened 2021-04-01 09:22 UTC by rluders

This PR solves the issue described on #34 - by doing some small changes to the Dockerfiles and docker-compose file.

Also, it updates the README file with new instruction, and move some files around, in order to provide a better organization to the repository structure.

2021-04-02 12:06 UTC, basask requested changes
It looks like these changes broken the swagger tooling.
For example, `make swagger-editor` is not working anymore

2021-04-02 15:09 UTC, rluders commented
Just to track things up. We decide to remove the Swagger API schema from this repository, and also the `Makefile` related to the Swagger. From now on, the API schema should be declared inside every microservice repository. However, this repository will keep a docker-compose file that should be able to run all the mock APIs.

I'm not sure if it would be interesting to also keep the mocks under a very simple API gateway service, but, let's make it as simple as possible for now.

2021-04-03 07:54 UTC, rluders commented on swagger/docker-compose.yml
> +      OPENAPI_MOCK_SPECIFICATION_URL: 'https://raw.githubusercontent.com/sumelms/microservice-account/main/swagger/account-api.yaml'
This URL is gonna be valid only after [this PR](https://github.com/sumelms/microservice-account/pull/14) gets merged.

2021-04-04 22:26 UTC, basask approved these changes

2021-04-10 14:41 UTC, arianerocha approved these changes

2021-04-18 11:08 UTC, merged